-- Nuxt Expense Tracker schema (Oracle)
-- Run against the app schema (expense_app) after the database is up.

CREATE TABLE categories (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE expenses (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id NUMBER NOT NULL REFERENCES categories(id),
  description VARCHAR2(200) NOT NULL,
  amount      NUMBER NOT NULL,
  spent_on    DATE DEFAULT SYSDATE NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE income (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description  VARCHAR2(200) NOT NULL,
  amount       NUMBER NOT NULL,
  received_on  DATE DEFAULT SYSDATE NOT NULL,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Starter categories
INSERT INTO categories (name) VALUES ('Food');
INSERT INTO categories (name) VALUES ('Transport');
INSERT INTO categories (name) VALUES ('Housing');
INSERT INTO categories (name) VALUES ('Entertainment');
INSERT INTO categories (name) VALUES ('Other');

COMMIT;
